---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clinic-deploy
  labels:
    myversion: "1"
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: clinic-front
  template:
    metadata:
      labels:
        app: clinic-front
    spec: # specification du pod
      containers:
        - name: springboot
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"

          startupProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            timeoutSeconds: 6
            periodSeconds: 9
            initialDelaySeconds: 6
            failureThreshold: 60

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            timeoutSeconds: 3
            periodSeconds: 9

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            timeoutSeconds: 3
            periodSeconds: 9
